version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"    

  organia_db:
    image: postgres
    environment:
      POSTGRES_DB: organia
      POSTGRES_PASSWORD: 1234
    ports:
      - "5400:5432"
    volumes:
      - ./app/database/data:/var/lib/postgres/data 


