version: '3'

services:
  web:

    build: .
    ports:
      - "8000:8000"
    command: ["sleep", "infinity"]
    volumes:
    # Update this to wherever you want VS Code to mount the folder of your project
    - ..:/workspaces:cached

  organia_db:
    image: postgres
    environment:
      POSTGRES_DB: organia
      POSTGRES_PASSWORD: 1234
    ports:
      - "5400:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./app/database/data:/var/lib/postgres/data